### ISSUE TITLE
Ta bort outline

### ISSUE THREAD

**Issue by itpastorn** [saraclasson/webbutveckling-1#11]
````css
.subpage .hwrap > a,
nav {
    margin-right: 10px;
    flex: 0 1 20%;
    min-width: 146px;
    margin-right: 10px;
    /* outline: 1px solid; */
}
````
