### ISSUE TITLE
Lägg till regel för subpage

### ISSUE THREAD

**Issue by itpastorn** [saraclasson/webbutveckling-1#13]
Den andra regeln nedan saknas i din kod

````css
.subpage .hwrap {
    justify-content: space-between;
}
.subpage h2 {
    text-align: center;
}
````
