### ISSUE TITLE
Lägg till regel för figure img

### ISSUE THREAD

**Issue by itpastorn** [saraclasson/webbutveckling-1#14]
Mittenregeln saknas i din kod

````css
figure {
    float: left;
    margin: 0;
}
figure img {
    width: 128px;
    height: 128px;
}
figcaption {
    font: italic bolder 110% sans-serif;
    font-family: inherit;
    text-align: center;
    text-transform: uppercase;
    color: #666;
}
````
