### ISSUE TITLE
Duplicerad body-regel rad 107-109

### ISSUE THREAD

**Issue by itpastorn** [saraclasson/webbutveckling-1#4]
Du har duplicerat body-selektorn. Regeln på rad 107-109 är onödig.
````css
body {
    font-family: "Helvetica Neue", "Liberation Sans", Calibri, Arial, sans-serif;
}
````
Flytta rad 108 till rad 13.

Alla andra issues kommer utgå från förändrad radnumrering som om den förra var gjord!
