### ISSUE TITLE
Flytta runt dina regler så att de hamnar på rätt ställe

### ISSUE THREAD

**Issue by itpastorn** [saraclasson/webbutveckling-1#7]
Dina regler hamnar ofta i fel sektion. Flytta dem så att de hamnar enligt följande.

Notera att du ska slå ihop reglerna för body och .startpage.

Skriv om denna selektor:
````css
.startpage header,
.startpage footer {
````
Till detta:
````css
body > header,
body > footer {
````

Reglernas ordningen enligt boken:
````css
@charset "UTF-8";
/*
=============================================================
Global rules
=============================================================
*/
html {
}
body {
}
body > header,
body > footer {
}
/*
section, header, footer, nav, div[role=main] {
    outline: 1px solid red;
}
*/
/*
=============================================================
Rules for reusable components
=============================================================
*/
.dborder {
}
/*
=============================================================
Page header, all pages
=============================================================
*/
header {
}
.hwrap {
}
.hwrap > a {
}
h1 {
}
h1::first-letter {
}
.startpage h1 {
}
.tagline {
}
/*
=============================================================
Page footer rules
=============================================================
*/
footer {
}
/*
=============================================================
Main site navigation
=============================================================
*/
.menu > li,
.menu > h2 {
}
.menu a {
}
.menu {
}
.menu li {
}
.menu a:link,
.menu a:visited {
}
.menu a:focus,
.menu a:hover {
}
.menu a:active {
}
/*
=============================================================
Start page rules
=============================================================
*/
.startpage .logo {
}
.startpage section {
}
/*
=============================================================
Subpages
=============================================================
*/
.subpage .hwrap > a,
nav {
}
.subpage .logo {
}
.subpage .hwrap > h1,
div[role=main] {
}
.subpage h1 {
}
h1 > span {
}
.subpage .hwrap {
}
.subpage h2 {
}
article {
}
article:last-child {
}
figure {
}
figure img {
}
figcaption {
}
article p {
}
/*
=============================================================
Tables
=============================================================
*/
table {
}
thead {
}
th, td {
}
th {
}
th:not(:last-child) {
}
td {
}
tr:target {
}
tr:hover {
}
tr {
}

/*
=============================================================
Nivo Slider
=============================================================
*/
.nivo-caption {
}

/*
=============================================================
Forms (contact page)
=============================================================
*/
fieldset {
}
legend {
}
form p {
}
label {
}
.reqfield {
}
input[type=text],
input[type=email],
textarea {
}
textarea {
}
input[type="submit"] {
}

/*
=============================================================
Blog page, show and edit
=============================================================
*/

/*
=============================================================
Adaptive design
=============================================================
*/
.tagline button {
}
@media (max-width: 750px) {
}
@media (max-width: 650px) {
}
@media (max-width: 550px) {
}
/* 475 px was a breakpoint for flex design on subpages */
@media (max-width: 476px) {
}
@media (max-width: 380px) {
}
````
