### ISSUE TITLE
Fontfamiljen cursive ska ha litet c

### ISSUE THREAD

**Issue by itpastorn** [saraclasson/webbutveckling-1#8]
````css
h1 {
    font-family: 'Merienda One', cursive; /* Litet c */
}
````
Och ytterligare ett ställe.
